#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# Remove all existing rules before loading.
bspc rule -r "*"

# BSPWM configuration.
bspc config automatic_scheme              longest_side
bspc config split_ratio                   0.50
bspc config border_width                  3
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_follows_monitor       false
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config center_pseudo_tiled           true
bspc config ignore_ewmh_focus             false

# Gaps and padding.
bspc config window_gap       15
bspc config bottom_padding   0
bspc config left_padding     0
bspc config right_padding    0
bspc config top_padding     35

# mod1=Alt, mod4=super, mod5=AltGr
bspc config pointer_modifier mod1
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

# Borders and colors.
bspc config normal_border_color   "#282c34"
bspc config active_border_color   "#282c34"
bspc config focused_border_color  "#e06c75"
bspc config presel_feedback_color "#e06c75"

# Custom tiling rules.
bspc rule -a Zathura state=tiled

# Swap Caps Lock with Left Control.
setxkbmap -option ctrl:nocaps

# Update x-cursor to avoid enlargement.
# To avoid "X" cursor outside windows, install lxappearance.
xsetroot -cursor_name left_ptr

# Set whatever wallpaper were last used by feh.
"$HOME/.fehbg" &

# Launch polybar.
bash "$HOME/.config/polybar/launch.sh" > /dev/null 2>&1

# Modify key repeat.
xset r rate 350 30
# xset r off

# -----------------------------------------------
# Autostart
#
nm-applet &
blueman-applet &
picom -b
ibus-daemon -drxR
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
systemctl restart --user redshift-gtk

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
xss-lock --transfer-sleep-lock -- i3lock -c 292929 --nofork &

# -----------------------------------------------
# Scripts
#
# Run monitor setup script.
bash "$HOME/Development/Repositories/dotfiles/scripts/bspwm-monitor-setup.sh" &
